### ISSUE TITLE
wrong error message

### ISSUE THREAD

**Issue by berengma** [acmgit/minetest_poi#7]
lets say you have a poi named "bungalow" and it belongs to the categorie "default"

then you decide you want to change it to the categorie "buildings", but when entering
the command you cant remember exactly the categorie name so you write:

/poi_set bungalow, building

You will get the error message : "PoI <bungalow> exists".
Instead it would be nice if you would get the answer "categorie <building> does not exist" :)
Like that you  would know you spelled something wrong.

**Comment by acmgit** [comment]
The error-message should tell you for the first, that a PoI with this Name exists. Independ from the Categorie, there shouldn't exist a PoI with the same name at the same time.

If the Name exists, but you give another Categorie, then you change only the Categorie. If you give an unknown Categorie, it will be set to Categorie 1 per default.

But you're right, i've extended now the Message to:
 < PoI> in Categorie <Categorienumber - Categoriename> already exists ;-).

**Comment by berengma** [comment]
I guess it does not solve the problem :)

Wouldn't it be possible, if I only want to give a new categorie, to check for the entered categorie to be in the categories.lua or not and to give an error message if not.

like in the example in my first post:
/poi_set bungalow, building

Now the code checks first for Poi "bungalow". OK exists. no Error
Next code checks for the categories. Old categorie "default", new given categorie "building". ERROR !
                            There is no categorie "building" in categories.lua. It should be "buildings" !!

Exactly this case happened to me when reconfiguring the categories in Jungle-server :D It took me
a while until I  found out that only one char was false/missing :)

**Comment by acmgit** [comment]
Right, but than i need a second Routine, which checks the categorie, if only it exists. The current routine checks the exists of an categorie, if it don't exists, it set it to categorie 1. This is for the case, that you set a POI without a categorie. So nobody can set a new POI without a Categorie.
Seems, that i have to redesign this routine 😁.

**Comment by acmgit** [comment]
Now, if you try to change an existing POI to an unknown Categorie, you will get an Error-Message.
If you try to set a new POI to an unknown Categorie, you get a Warning-Message, but the new POI will set to Categorie 1 per default ;-).
