### ISSUE TITLE
Choice at the GUI to set to the initial Listing.

### ISSUE THREAD

**Issue by acmgit** [acmgit/minetest_poi#9]
How could it be, if the Categorie-Button has a Categorie to choose, which isn't a real categorie, but gives you the List from the Start of the GUI.
The List without an Categorie but ALL POI's. ;-).

**Comment by berengma** [comment]
That should't be too difficult. I will look into it. 
The plan was to add even a larger gui for poi priv owners, to set and manage them more comfortable :)

**Comment by acmgit** [comment]
You're in my head. The same what i've thought  😁.
